// <auto-generated />
using System;
using JQ.PokemonLibrary.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JQ.PokemonLibrary.DB.Migrations
{
    [DbContext(typeof(PokemonDBContext))]
    [Migration("20211011003112_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JQ.PokemonLibrary.DB.Model.Pokemon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("Generation")
                        .HasColumnType("int");

                    b.Property<int>("HP")
                        .HasColumnType("int");

                    b.Property<bool>("Legendary")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("SpecialMoveAttack")
                        .HasColumnType("int");

                    b.Property<int>("SpecialMoveDefense")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<int>("Type1")
                        .HasColumnType("int")
                        .HasColumnName("Type1");

                    b.Property<int>("Type2")
                        .HasColumnType("int")
                        .HasColumnName("Type2");

                    b.HasKey("Id");

                    b.HasIndex("Type1");

                    b.HasIndex("Type2");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("JQ.PokemonLibrary.DB.Model.PokemonType", b =>
                {
                    b.Property<int>("IdPokemonType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPokemonType");

                    b.ToTable("PokemonType");
                });

            modelBuilder.Entity("JQ.PokemonLibrary.DB.Model.Pokemon", b =>
                {
                    b.HasOne("JQ.PokemonLibrary.DB.Model.PokemonType", "PokemonType1")
                        .WithMany()
                        .HasForeignKey("Type1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JQ.PokemonLibrary.DB.Model.PokemonType", "PokemonType2")
                        .WithMany()
                        .HasForeignKey("Type2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PokemonType1");

                    b.Navigation("PokemonType2");
                });
#pragma warning restore 612, 618
        }
    }
}
